### ISSUE TITLE
504 Gateway Timeout after signin with email and password

### ISSUE THREAD

**Issue by cezarlz** [wedeploy/wedeploy-sdk-js#220]
### Are you opening a bug report?

Yes

### Environment

JavaScript SDK version: 4.1.0

Environment:
  Browser: Chrome v62
  Node: No
  ReactNative: No
  React VR: No
  Electron: No

### Steps to Reproduce

1. Setup your auth: `WeDeploy.auth('yourhost');`
2. SignIn using email and password:`auth.signInWithEmailAndPassword('email', 'password');`
3. The SDK will call the `/oauth/token` and then it will call the `/user`.
4. You will receive 504 Gateway Timeout

### Expected Behavior

The expected behavior is storage the user and returns 200 when trying to get the user's data.

### Actual Behavior

Returning 504 Gateway Timeout after `signInWithEmailAndPassword`.

![xwidwspidz](https://user-images.githubusercontent.com/954889/32461963-06560fd2-c338-11e7-80a0-b36593809eee.gif)

Log:
```
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.ext.jwt.JWT
spike[2340968c] INFO: HS384 not available
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.ext.jwt.JWT
spike[2340968c] INFO: HS512 not available
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.ext.jwt.JWT
spike[2340968c] INFO: RS384 not available
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.ext.jwt.JWT
spike[2340968c] INFO: RS512 not available
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.ext.jwt.JWT
spike[2340968c] INFO: ES384 not available
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.ext.jwt.JWT
spike[2340968c] INFO: ES512 not available
spike[2340968c] Nov 06, 2017 8:23:30 PM io.vertx.core.http.impl.HttpClientRequestImpl
spike[2340968c] SEVERE: java.net.UnknownHostException: auth: Name or service not known
spike[2340968c] Nov 06, 2017 8:24:00 PM io.vertx.core.net.impl.ConnectionBase
spike[2340968c] SEVERE: java.io.IOException: Connection reset by peer
```

### Reproducible Demo

```js
const auth = WeDeploy.auth('host');

auth.signInWithEmailAndPassword('email', 'password');

// check your connections
```

**Comment by cezarlz** [comment]
In this time, I've created auth services with different names and I've been getting the same error.

**Comment by ipeychev** [comment]
This error: `java.net.UnknownHostException: auth: Name or service not known` means there is no service with such id.

**Comment by cezarlz** [comment]
@ipeychev but do I need to create a service with this id? Can't I create with my own id?

**Comment by ipeychev** [comment]
Yes, it should be [possible](https://wedeploy.com/docs/auth/getting-started/). My best **guess** is that Auth service in your project failed to deploy and that's why it wasn't found. Please check again your project, look if you have such a service, check the id, check the deployment status. Check also if you are creating Auth instance with the proper url, like `WeDeploy.auth('<id>-<myproject>.wedeploy.io')`
Take a look on the Auth boilerplate in [action](https://boilerplateauth.wedeploy.io). The code is [here](https://github.com/wedeploy/boilerplate-auth/tree/web). If everything looks fine, but it still doesn't work, please create an Auth service with `auth` id to verify. If the problem is with the id, I will move the issue to the proper repository.

Also, please note the following: this repository is for issues related to WeDeploy SDK JS. Next time please contact support. Hope you understand!

Thanks,

**Comment by cezarlz** [comment]
Ok, I will check all of them. thanks!

**Comment by cezarlz** [comment]
@ipeychev using the name `auth` as the id, it works perfectly! but when I install an auth service using another id like `foo-project.wedeploy.io` it doesn't work but `auth-project.wedeploy.io` works!

I've been following the documentation exactly as it describes and doing all tutorials just to have sure I'm doing the right steps.

I've been facing other issues on "infrastructure". For instance, if I delete a service with a name, delete it and create another service with the same name, this last one "imports" the data of the deleted one. Do the test: create a data service with the name `test`, insert some data on `users` database, delete it, create an auth service with the same name, `test` and you will see the old data on this new service. For me, new service is a new service.

Thanks for your help!

**Comment by ipeychev** [comment]
Okay, I will open issues where it is appropriable. Thanks for the report and sorry for the issues!
